### ISSUE TITLE
[Bug]: unable to run via docker per instructions

### ISSUE THREAD

**Issue by kobuki** [billchurch/webssh2#317] opened 2022-11-06 14:48 UTC
### What happened?

Running the app via docker using the following command fails:

```
$ docker run --name webssh2 -d -p 2222:2222 -v $PWD/config.json:/usr/src/config.json billchurch/webssh2
f41f6df65f26172b044e3474632af6ca1474238565a14e9f7ef8af9bd8f45f29
```

Container exits here instantly. Config file attached. Made from sample config file in Git. Output of `docker logs` below.

[config.json.txt](https://github.com/billchurch/webssh2/files/9946089/config.json.txt)

### Node Version

N/A

### NPM Version

N/A

### Server OS Version

Debian 10.12

### WebSSH2 release version

N/A

### OS and Version of SSH server

N/A

### Browser Version

N/A

### Relevant log output

```shell
$ docker logs webssh2
WebSSH2 service reading config from: /usr/src/config.json
/usr/src/server/app.js:22
  origins: config.http.origins,
                       ^

TypeError: Cannot read property 'origins' of undefined
    at Object.<anonymous> (/usr/src/server/app.js:22:24)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/src/index.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
```

**Comment by tip2tail** [comment] 2023-01-28 23:34
@kobuki @billchurch did you find a fix for this?
I had webssh2 working, tweaked the config file and now cannot get it to run at all - even when I revert back to the initial file.
Same error

**Comment by tip2tail** [comment] 2023-01-29 10:09
I have done some digging and I have found that the built version of `server/app.js` within the docker image itself differs from the defined source version in a couple of places.  See higlighted below:
![image](https://user-images.githubusercontent.com/1719754/215319238-575b934b-b6d5-4d96-bfe0-82e0d3cefa6a.png)

**Comment by tip2tail** [comment] 2023-01-29 14:50
Just to follow up - I have attempted to build a completely fresh version of this with docker and still get the same cursorBlink error

**Comment by billchurch** [comment] 2023-02-06 17:26
@kobuki probably a better way you could phrase that to the only developer working on a project for free...

The example `config.json` you're pulling from `main` is the development branch. the `0.4.6` tag would contain the correct example config.json (as well as the correct README).

**Closed by billchurch** 2023-02-06 17:26 UTC
Labels: bug

**Comment by billchurch** [comment] 2023-02-06 17:33
@kobuki you can feel free to pull billchurch/webssh2:main if you want the current development branch, but its probably not what you want.

**Comment by kobuki** [comment] 2023-02-06 17:35
No, I'm thankful for every piece of free software, including yours, that I have access to. I'm saying this as someone who also works on OSS projects even here. But as one I usually _try_ to produce a master that can be used as-is and work on feature branches otherwise. I was a little baffled on why a code that's being regularly maintained refuses to even load its config. But, no offense was intended, I shoulda chosen my wording a bit better, maybe.

In any case, I can try out webssh2 in 0.4.6 now, thanks for the hints!

**Comment by billchurch** [comment] 2023-02-06 17:42
if you're using docker, you don't need to checkout anything. A proper config for the version is the only thing you need, which is going to be stored under the tag for that version.

**Comment by billchurch** [comment] 2023-02-06 18:36
I updated docker page as well...

**Comment by tip2tail** [comment] 2023-02-06 21:22
@billchurch Very much appreciated and thanks for the detail on what the root cause was.
Glad to have helped!

Thanks again
M
