### ISSUE TITLE
Not redirect after failed auth to /reauth

### ISSUE THREAD

**Issue by nebuchad908** [billchurch/webssh2#200] opened 2020-06-22 13:17 UTC
Hello.

If I try to log in as a user with password authorization is disabled (sshd_config -> PasswordAuthentication no), the window will not be reloaded and I will not be able to log in as another user.

![image](https://user-images.githubusercontent.com/15632675/85291826-ab032380-b4a3-11ea-9c14-7d693ccc96c2.png)

This is not a critical bug, but I think, it is possible to handle this exception.

Thanks

**Comment by billchurch** [comment] 2020-09-17 11:59
duplicate of #141 I'm still not able to reproduce this unfortunately.

**Closed by billchurch** 2020-09-17 11:59 UTC
