### ISSUE TITLE
WEBSOCKET SERVER DISCONNECTED: transport error

### ISSUE THREAD

**Issue by mjrudnik** [billchurch/WebSSH2#39] opened 2018-02-05 08:57 UTC
Hey,

whenever i open vim or bash inside the WebSSH2 terminal i get a transport error.

What am i doing wrong?

**Comment by billchurch** [comment] 2018-02-06 15:18
Good question. I'm not able to re-create this issue...

Can you provide:
- Version of node WebSSH2 is running on
- OS name/version, release of SSH, and version of vi that your ssh server is running 

And I can investigate further.

**Comment by mjrudnik** [comment] 2018-02-07 09:37
thanks for your response,

I have cloned the repo and i am currently on following commit: 
```
commit f890c46de33e8c5ccbc82adc0a53a17fa4a5d242
Author: billchurch <wmchurch@gmail.com>
Date:   Tue Jan 30 18:35:13 2018 -0500

    fix binaries
```
That's my vim version: `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)`

`> uname -a ` says: 
`Linux mail 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

`bash --version` shows:
`GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)`

```
WebSSH2 Login: user=blub from=127.0.0.1 host=127.0.0.1 port=2135 sessionID=lIMw3s8WOlbtDjg0PP8p7a2xriIUwNAV/xWiKYKqF62kHVu_YAAAX allowreplay=false term=xterm-color
WebSSH2 Logout: user=blub from=127.0.0.1 host=127.0.0.1 port=2135 sessionID=lIMw3s8WOlbtDjg0PP8p7a2xriIUwNAV/xWiKYKqF62kHVu_YAAAX allowreplay=false term=xterm-color
WebSSH2 error: transport close
```

**Comment by billchurch** [comment] 2018-02-07 11:13
Perfect. I’ll work to try and reproduce. Something else you might try in the meantime, it will be information overload but you can run “export DEBUG=*” and then “npm run start” should output every key character and every ssh and websocket packet. May point to something.

**Comment by mjrudnik** [comment] 2018-02-07 21:36
I tested it again mit `DEBUG=* npm start 2> webssh.log`
You can find the output in the file below. Maybe this will help. 

[webssh.log](https://github.com/billchurch/WebSSH2/files/1704842/webssh.log)

**Comment by billchurch** [comment] 2018-02-08 14:31
Nothing seems immediately obvious from the log. Can you run cat /etc/issue, I'm on Ubuntu 14.04.2 LTS and my VIM is:
- VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:02)

**Comment by billchurch** [comment] 2018-02-08 14:36
Just had a thought, I recently updated socket.io to 2.x, do me a favor and run:

npm --save install socket.io@1
npm run build

and try again and tell me if that changes anything.

**Comment by mjrudnik** [comment] 2018-02-08 18:59
After installing `npm --save install socket.io@1` it finally works!
But vim and tmux sessions open in small windows with 80 characters in width.
Do you know why this happens?

**Comment by billchurch** [comment] 2018-02-08 20:28
hmmm... what does "tput cols" and "tput lines" say before you run vim and tmux?

**Comment by billchurch** [comment] 2018-02-10 03:23
@mjrudnik check out my latest commits, they're not in a release yet but did a lot with resizing and terminal geometry, i think you'll like it... Let me know if this solves your problem.

**Comment by mjrudnik** [comment] 2018-02-10 11:46
`tput cols` says 80 and `tput lines` says 24 even after pulling your latest changes.

**Comment by mjrudnik** [comment] 2018-02-10 11:49
Okay, i found out that when resizing my chrome window it changes width and height to the correct values.

**Comment by billchurch** [comment] 2018-02-10 19:14
Yes, that was a tricky one to figure out, I just released v0.2.0 which should handle a lot of resize use cases across a lot of browsers. I'm going to close this out now, if you're still having issues let me know and thanks for reporting this!

**Comment by billchurch** [comment] 2018-02-10 19:14
fixed by #43

**Closed by billchurch** 2018-02-10 19:14 UTC
Labels: question

**Comment by ccinoo** [comment] 2018-04-12 15:31
run:

npm --save install socket.io@1

npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ socket.io@1.7.4
updated 1 package in 18.383s

**Comment by entriver** [comment] 2018-08-23 12:56
Hello Bill, I have installed WebSSH2 on windows10 system.  I'm trying to open vim (installed using gvim81.exe from www.gvim.org)  I'm getting the below message.  Can you please help?
C:\Program Files\OpenSSH\home\riverwba>vim test.json
Vim: Error: This version of Vim does not run in a Cygwin terminal

**Comment by billchurch** [comment] 2018-09-07 14:39
@entriver not sure this is related to anything with WebSSH2 I can assist with. Sounds like your problem might be with Cygwin or Vim on Cygwin.

**Comment by entriver** [comment] 2018-09-08 05:32
Hello Bill, Sorry forgot to update this post.  The issue is not related to WebSSH2. There is a openssh service available which is cygwin based. "Vim: Error: This version of Vim does not run in a Cygwin terminal" appears, if you are using wrong OpenSSH service.  We should install openssh as described in your manual.
