### ISSUE TITLE
Public Key authentication available / contemplated?

### ISSUE THREAD

**Issue by novak-services** [billchurch/webssh2#329] opened 2023-04-01 09:02 UTC
That is a very neat tool. But when I am using SSH, I mostly go for Public Key authentication (using private keys on the local system and the public key is known to the server). This also gives best security.

Is this currently possible or in any way anticipated?

**Comment by billchurch** [comment] 2023-08-22 11:22
It is planned, but no ETA. duplicate of #247

**Closed by billchurch** 2023-08-22 11:22 UTC
Labels: duplicate
